[project]
name = "darts-devkit"
version = "1.0.0"
description = "devkit for DARTS database"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3"
]
license = { file = "LICENSE.md" }


dependencies = [
    "tqdm>=4.67.3",
    "pillow>=12.2.0",
    "numpy>=2.2.6",
    "pydantic>=2.12.5",
    "packaging>=26.2",
    "typing-extensions>=4.16.0",
]

[dependency-groups]
dev = [
    "mypy>=2.2.0",
    "types-tqdm>=4.67.3.20260205",
    "ruff>=0.15.0",
    "pipdeptree>=2.30.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-random-order>=1.2.0",
    "scipy-stubs>=1.15.3.0",
    "types-shapely>=2.1.0.20260518",
    "pyquaternion>=0.9.9",
]

[project.optional-dependencies]

rerun_visualizer = [
    "rerun-sdk>=0.31.1",
    "matplotlib>=3.10.8",
]
docs = [
    "sphinx>=8.1.3",
    "sphinxcontrib-mermaid>=2.0.0",
    "sphinx-immaterial>=0.13.9",
]
polygon_overlap_evaluator = [
    "pyquaternion>=0.9.9",
    "scipy>=1.15.3",
    "shapely>=2.1.2",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812",  # Formatter conflicts
  "S324",   # Probable use of insecure hash functions in `hashlib`: `md5`
  "UP046",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.coverage.run]
omit = ["*/__init__.py"]

[[tool.mypy.overrides]]
module = ["pyquaternion"]
ignore_missing_imports = true
