[project]
name = "darts-devkit"
version = "1.1.1"
description = "devkit for DARTS database"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3"
]
license = { file = "LICENSE.md" }


dependencies = [
    "tqdm>=4.67.3",
    "pillow>=11.3.0",
    "numpy>=1.26.4",
    "pydantic>=2.12.5",
    "packaging>=26.2",
    "typing-extensions>=4.16.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "types-tqdm>=4.67.3.20260205",
    "ruff>=0.15.0",
    "pipdeptree>=2.28.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-random-order>=1.2.0",
    "types-shapely>=2.1.0.20250917",
    "pyquaternion>=0.9.9",
    "build>=1.4.4",
    "twine>=6.2.0",
]

[project.optional-dependencies]

rerun_visualizer = [
    "rerun-sdk>=0.26.2",
    "matplotlib>=3.9.4",
]
docs = [
    "sphinx>=7.4.7",
    "sphinxcontrib-mermaid>=1.2.3",
    "sphinx-immaterial>=0.12.5",
]
polygon_overlap_evaluator = [
    "pyquaternion>=0.9.9",
    "scipy>=1.13.1",
    "shapely>=2.0.7",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812",  # Formatter conflicts
  "S324",   # Probable use of insecure hash functions in `hashlib`: `md5`
  "UP046",
  "CPY001", # Missing copyright notice at top of file
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.coverage.run]
omit = ["*/__init__.py"]

[[tool.mypy.overrides]]
module = ["pyquaternion", "scipy.optimize"]
ignore_missing_imports = true
